name: Build 8Ball Dumper Fixed
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17
        cache: gradle
    - name: Build Module
      run: |
        chmod +x ./gradlew
        # حقن اسم اللعبة مباشرة
        sed -i 's/moduleDescription = "/moduleDescription = "(com.miniclip.eightballpool) /g' module.gradle
        sed -i "s/com.game.packagename/com.miniclip.eightballpool/g" module/src/main/cpp/game.h
        # بدء البناء
        ./gradlew :module:assembleRelease
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Zygisk-Dumper-8BP-2026
        # التصحيح هنا: أشرنا للمجلد وليس لملف مضغوط
        path: out/magisk_module_release/
